# Generated by Django 3.2.13 on 2022-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysCodeTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.CharField(choices=[('0', '正常'), ('1', '已删除')], default='0', max_length=1, verbose_name='删除标记(默认0未删除)')),
                ('data_exchange', models.CharField(default='0', max_length=1, verbose_name='数据交换位')),
                ('code', models.CharField(max_length=10, verbose_name='代码值')),
                ('name', models.CharField(max_length=100, verbose_name='相应名称')),
                ('code_table', models.CharField(max_length=10, verbose_name='代码表名')),
                ('valid_status', models.CharField(choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=1, verbose_name='有效状态(默认Y有效)')),
            ],
            options={
                'verbose_name': '公共代码表值',
                'verbose_name_plural': '公共代码表值',
                'db_table': 'sys_code_tables',
            },
        ),
        migrations.CreateModel(
            name='SysCodeTablesManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.CharField(choices=[('0', '正常'), ('1', '已删除')], default='0', max_length=1, verbose_name='删除标记(默认0未删除)')),
                ('data_exchange', models.CharField(default='0', max_length=1, verbose_name='数据交换位')),
                ('code_table', models.CharField(max_length=10, verbose_name='代码表')),
                ('code_table_name', models.CharField(max_length=50, verbose_name='代码表名称')),
                ('valid_status', models.CharField(choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=1, verbose_name='有效状态(默认Y有效)')),
            ],
            options={
                'verbose_name': '系统码表',
                'verbose_name_plural': '系统码表',
                'db_table': 'sys_code_tables_manage',
            },
        ),
        migrations.CreateModel(
            name='SysOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.CharField(choices=[('0', '正常'), ('1', '已删除')], default='0', max_length=1, verbose_name='删除标记(默认0未删除)')),
                ('data_exchange', models.CharField(default='0', max_length=1, verbose_name='数据交换位')),
                ('operator_id', models.CharField(max_length=100, verbose_name='操作人id')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('operator_account', models.CharField(max_length=100, verbose_name='操作账号')),
                ('operator_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP地址')),
                ('content', models.CharField(max_length=1000, verbose_name='操作内容')),
            ],
            options={
                'verbose_name': '系统操作日志信息表',
                'verbose_name_plural': '系统操作日志信息表',
                'db_table': 'sys_operate_log',
            },
        ),
        migrations.CreateModel(
            name='SysRegionalism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.CharField(choices=[('0', '正常'), ('1', '已删除')], default='0', max_length=1, verbose_name='删除标记(默认0未删除)')),
                ('data_exchange', models.CharField(default='0', max_length=1, verbose_name='数据交换位')),
                ('code', models.CharField(max_length=10, verbose_name='行政区划代码')),
                ('name', models.CharField(max_length=100, verbose_name='行政区划名称')),
                ('parent_node', models.CharField(max_length=10, verbose_name='父节点')),
                ('valid_status', models.CharField(choices=[('Y', '有效'), ('N', '无效')], default='Y', max_length=1, verbose_name='有效状态(默认Y有效)')),
            ],
            options={
                'verbose_name': '系统行政区划代码表',
                'verbose_name_plural': '系统行政区划代码表',
                'db_table': 'sys_regionalism',
            },
        ),
    ]
