# Generated by Django 3.2.13 on 2022-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='menu_code',
            field=models.IntegerField(verbose_name='菜单编号'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='menu_parent_code',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='菜单父级编号'),
        ),
        migrations.AlterField(
            model_name='sysrolemenu',
            name='menu_id',
            field=models.IntegerField(verbose_name='菜单编号'),
        ),
    ]
