# Generated by Django 4.0.5 on 2022-07-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='role_describe',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='角色描述'),
        ),
    ]
