# Generated by Django 3.2.13 on 2022-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220709_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='menu_parent_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='菜单父级编号'),
        ),
    ]
