# Generated by Django 3.2.13 on 2022-07-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmininfo',
            name='recent_date',
            field=models.DateTimeField(verbose_name='最近一次登录时间'),
        ),
    ]
